
const CONSTANTS = {
    FETCH_POSTS_QUERY:'FETCH_POSTS_QUERY',
    REGISTER_USER:'REGISTER_USER',
    LOGIN_USER:'LOGIN_USER',
    CREATE_POST:'CREATE_POST',
    LIKE_POST:'LIKE_POST',
    SINGLE_POST_QUERY:'SINGLE_POST_QUERY',
    CREATE_COMMENT:'CREATE_COMMENT',
    DELETE_POST:'DELETE_POST',
    DELETE_COMMENT:'DELETE_COMMENT',
}

export default CONSTANTS;